### ISSUE TITLE
Uncaught, unspecified, "error" event crashes sever after several hours.

### ISSUE THREAD

**Issue by JSideris** [Bizorke/Saucers.Space#178]
Apparently this is caused by an arrow function trying to use a this keyword (maybe try testing that). 

Even then, it's unclear.

https://stackoverflow.com/questions/41373710/uncaught-unspecified-error-event

**Comment by JSideris** [comment]
Happened when the router got unplugged. It's 100% websocket related.

![image](https://user-images.githubusercontent.com/8083793/42528203-c7d0ca18-8448-11e8-86bd-17c39cdbd776.png)

**Comment by JSideris** [comment]
Might be related to #186. Testing needed.

**Comment by JSideris** [comment]
Hasn't crashed since resolving 186. Started after adding discord logging. Seems like he most obvious culprit.

**Comment by JSideris** [comment]
It's still crashing. 

```
Exception has occurred: Error
Error: Uncaught, unspecified "error" event. ([object Object])
    at Client.emit (events.js:163:17)
    at WebSocketConnection.onError (c:\Users\josh_\Desktop\saucers.space\ufo_p2_pixi\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:374:17)
    at WebSocket.onError (c:\Users\josh_\Desktop\saucers.space\ufo_p2_pixi\node_modules\discord.js\node_modules\ws\lib\event-target.js:128:16)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at _receiver.cleanup (c:\Users\josh_\Desktop\saucers.space\ufo_p2_pixi\node_modules\discord.js\node_modules\ws\lib\websocket.js:211:14)
    at Receiver.cleanup (c:\Users\josh_\Desktop\saucers.space\ufo_p2_pixi\node_modules\discord.js\node_modules\ws\lib\receiver.js:557:13)
    at WebSocket.finalize (c:\Users\josh_\Desktop\saucers.space\ufo_p2_pixi\node_modules\discord.js\node_modules\ws\lib\websocket.js:206:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
```

**Comment by JSideris** [comment]
Ok. https://github.com/discordjs/discord.js/issues/2523

Fixed.
